"""
Database models for the LLM Gateway.

Schema overview:
  users              – App users with role (admin / user), plus a flag for the default bootstrap admin
  refresh_tokens     – JWT refresh token tracking (existing)
  providers          – LLM provider configs (openai, gemini, ollama, etc.)
  provider_api_keys  – Multiple encrypted API keys per provider
  models             – Available LLM models tied to a provider
  gateway_api_keys   – API keys generated by users for hitting the gateway endpoints
  api_key_model_permissions – Links a gateway API key to allowed models (with token caps, etc.)
  permission_requests – Users request access to models; admin approves / rejects
  environment_variables – Encrypted key-value store (admin-only visibility)
"""

from sqlalchemy import (
    Column,
    Integer,
    String,
    DateTime,
    ForeignKey,
    Boolean,
    Text,
    Enum as SAEnum,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum
import uuid

from app.db.database import Base


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class UserRole(str, enum.Enum):
    admin = "admin"
    user = "user"


class PermissionRequestStatus(str, enum.Enum):
    pending = "pending"
    approved = "approved"
    rejected = "rejected"


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def generate_uuid():
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Users & Auth
# ---------------------------------------------------------------------------

class User(Base):
    """User model - stores user info, authentication, and role."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(100), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)

    # Role: admin or user
    role = Column(SAEnum(UserRole), default=UserRole.user, nullable=False)

    # Whether this is the auto-created default admin (username=admin, password=admin).
    # Once a real admin is created, this user gets deleted.
    is_default_admin = Column(Boolean, default=False, nullable=False)

    # If True, the user must change their password on next login
    must_change_password = Column(Boolean, default=False, nullable=False)

    # Profile
    display_name = Column(String(100), default="")

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    refresh_tokens = relationship(
        "RefreshToken", back_populates="user", cascade="all, delete-orphan"
    )
    gateway_api_keys = relationship(
        "GatewayApiKey", back_populates="user", cascade="all, delete-orphan"
    )
    permission_requests = relationship(
        "PermissionRequest", back_populates="user", cascade="all, delete-orphan",
        foreign_keys="PermissionRequest.user_id",
    )


class RefreshToken(Base):
    """Stores refresh tokens for JWT authentication."""

    __tablename__ = "refresh_tokens"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token = Column(String(500), unique=True, index=True, nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user = relationship("User", back_populates="refresh_tokens")


# ---------------------------------------------------------------------------
# LLM Providers
# ---------------------------------------------------------------------------

class Provider(Base):
    """
    An LLM provider (e.g. OpenAI, Google Gemini, Ollama).
    Stores base configuration such as the API base URL.
    """

    __tablename__ = "providers"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)  # e.g. "openai"
    display_name = Column(String(100), nullable=False)        # e.g. "OpenAI"
    # Base URL for API calls (e.g. "https://api.openai.com/v1" or "http://localhost:11434")
    base_url = Column(String(500), nullable=True)
    # Provider type used by the code to pick the right adapter
    provider_type = Column(String(50), nullable=False)  # openai | gemini | ollama
    is_active = Column(Boolean, default=True, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    api_keys = relationship("ProviderApiKey", back_populates="provider", cascade="all, delete-orphan")
    models = relationship("LLMModel", back_populates="provider", cascade="all, delete-orphan")


class ProviderApiKey(Base):
    """
    Encrypted API keys for a provider.
    Multiple keys can be stored per provider (for rotation, rate-limit pooling, etc.).
    """

    __tablename__ = "provider_api_keys"

    id = Column(Integer, primary_key=True, index=True)
    provider_id = Column(Integer, ForeignKey("providers.id", ondelete="CASCADE"), nullable=False)
    # A human-readable label for the key (e.g. "prod-key-1", "backup")
    label = Column(String(100), default="default")
    # The encrypted API key value
    encrypted_key = Column(Text, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    provider = relationship("Provider", back_populates="api_keys")


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class LLMModel(Base):
    """
    A specific LLM model offered by a provider.
    E.g. "gpt-4o", "gemini-1.5-pro", "llama3:8b".
    """

    __tablename__ = "llm_models"

    id = Column(Integer, primary_key=True, index=True)
    provider_id = Column(Integer, ForeignKey("providers.id", ondelete="CASCADE"), nullable=False)
    # The model identifier as the provider expects it (e.g. "gpt-4o-mini")
    model_id = Column(String(200), nullable=False)
    # Human-friendly name
    display_name = Column(String(200), nullable=False)
    # Max context window / max tokens the model supports (informational)
    max_context_tokens = Column(Integer, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Unique together: one model_id per provider
    __table_args__ = (
        UniqueConstraint("provider_id", "model_id", name="uq_provider_model"),
    )

    # Relationships
    provider = relationship("Provider", back_populates="models")
    permissions = relationship("ApiKeyModelPermission", back_populates="model", cascade="all, delete-orphan")
    permission_requests = relationship("PermissionRequest", back_populates="model", cascade="all, delete-orphan")


# ---------------------------------------------------------------------------
# Gateway API Keys (user-facing)
# ---------------------------------------------------------------------------

class GatewayApiKey(Base):
    """
    API keys generated by users to authenticate against the gateway's /chat endpoint.
    Each key can have its own set of model-level permissions.
    """

    __tablename__ = "gateway_api_keys"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    # The actual key value (stored as a hash; the raw key is shown once at creation)
    key_hash = Column(String(255), unique=True, index=True, nullable=False)
    # A prefix of the key for display purposes (e.g. "gw-abc1***")
    key_prefix = Column(String(20), nullable=False)
    label = Column(String(100), default="default")
    is_active = Column(Boolean, default=True, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_used_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    user = relationship("User", back_populates="gateway_api_keys")
    permissions = relationship(
        "ApiKeyModelPermission", back_populates="api_key", cascade="all, delete-orphan"
    )


class ApiKeyModelPermission(Base):
    """
    Links a GatewayApiKey to a specific LLMModel with optional constraints.
    This is the permission that determines whether a user's API key can call a given model.
    """

    __tablename__ = "api_key_model_permissions"

    id = Column(Integer, primary_key=True, index=True)
    api_key_id = Column(Integer, ForeignKey("gateway_api_keys.id", ondelete="CASCADE"), nullable=False)
    model_id = Column(Integer, ForeignKey("llm_models.id", ondelete="CASCADE"), nullable=False)

    # Per-permission token caps (optional overrides)
    max_input_tokens = Column(Integer, nullable=True)   # None = no limit / use model default
    max_output_tokens = Column(Integer, nullable=True)

    is_active = Column(Boolean, default=True, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        UniqueConstraint("api_key_id", "model_id", name="uq_apikey_model"),
    )

    # Relationships
    api_key = relationship("GatewayApiKey", back_populates="permissions")
    model = relationship("LLMModel", back_populates="permissions")


# ---------------------------------------------------------------------------
# Permission Requests
# ---------------------------------------------------------------------------

class PermissionRequest(Base):
    """
    A user requests access to a model for one of their API keys.
    Admin can approve or reject.
    """

    __tablename__ = "permission_requests"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    api_key_id = Column(Integer, ForeignKey("gateway_api_keys.id", ondelete="CASCADE"), nullable=False)
    model_id = Column(Integer, ForeignKey("llm_models.id", ondelete="CASCADE"), nullable=False)

    status = Column(SAEnum(PermissionRequestStatus), default=PermissionRequestStatus.pending, nullable=False)
    # Optional message from the user explaining why they need access
    request_message = Column(Text, nullable=True)
    # Optional message from the admin when approving/rejecting
    admin_message = Column(Text, nullable=True)
    # Who processed the request
    reviewed_by = Column(Integer, ForeignKey("users.id"), nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="permission_requests", foreign_keys=[user_id])
    api_key = relationship("GatewayApiKey")
    model = relationship("LLMModel", back_populates="permission_requests")


# ---------------------------------------------------------------------------
# Environment Variables (admin-only encrypted KV store)
# ---------------------------------------------------------------------------

class EnvironmentVariable(Base):
    """
    Admin-only encrypted key-value store.
    Used for API keys, cost parameters, model limits, or any other sensitive config.
    Values are encrypted at rest using the application SECRET_KEY.
    """

    __tablename__ = "environment_variables"

    id = Column(Integer, primary_key=True, index=True)
    key = Column(String(200), unique=True, nullable=False, index=True)
    # Encrypted value
    encrypted_value = Column(Text, nullable=False)
    description = Column(Text, nullable=True)
    # If True, the value is treated as sensitive and never returned in plaintext via API
    is_secret = Column(Boolean, default=True, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
