apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llmgateway-env
  namespace: llmgateway
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: llmgateway-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/llmgateway/llmgateway/env
